---
baseURL: "/"
languageCode: "en-us"
title: "Replicated Help Center"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation and knowledgebase for Replicated."
googleAnalytics: "UA-61084834-1"

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"
  search_env: "staging"

  favicon: ""
  pagetitle: "Replicated"
  permalink: "#"

  docker_version_default: "17.12.1-ce"
  docker_version_minimum: "1.7.1"
  replicated_api_version_current: "2.21.2"
  replicated_latest_version: "2.21.2"
  replicated_latest_release_date: "May 29, 2018"

  swarm_docker_version_minimum: "1.13.1"
  swarm_docker_version_default: "17.12.2-ce"

  kubernetes_version_minimum: "1.9.3"
  kubernetes_version_default: "1.12.3"
  kubernetes_version: "1.9.3"

taxonomies:
  category: "categories"
  tag: "tags"
  kb-section: "kb-sections"

algolia:
  index: "help_center_staging"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Guides"
      Weight: 1
      URL: "/guides/"
    - Name: "Documentation"
      Weight: 2
      URL: "/docs/native/getting-started/overview/"
    - Name: "API Reference"
      Weight: 3
      URL: "/api/"
    - Name: "Community"
      Weight: 3
      URL: "https://help.replicated.com/community/"
---
