---
baseURL: "/"
languageCode: "en-us"
title: "Replicated Help Center"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation and knowledgebase for Replicated."
googleAnalytics: ""

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"
  search_env: "dev"

  matomo:
    host: "localhost:4000"
    site: "2"

  favicon: ""
  pagetitle: "Replicated"
  permalink: "#"

  docker_version_default: "18.09.2-ce"
  docker_version_minimum: "1.7.1"
  replicated_api_version_current: "2.35.0"
  replicated_latest_version: "2.35.0"
  replicated_latest_release_date: "April 30, 2019"

  swarm_docker_version_minimum: "1.13.1"
  swarm_docker_version_default: "18.09.2-ce"

  kubernetes_docker_version_minimum: "1.12.3"
  kubernetes_docker_version_default: "18.06.3"
  kubernetes_version: "1.13.5"

taxonomies:
  category: "categories"
  tag: "tags"
  kb-section: "kb-sections"

algolia:
  index: "help_center"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Guides"
      Weight: 1
      URL: "/guides/"
    - Name: "Documentation"
      Weight: 2
      URL: "/docs/kubernetes/getting-started/overview/"
    - Name: "API Reference"
      Weight: 3
      URL: "/api/"
    - Name: "Community"
      Weight: 3
      URL: "https://help.replicated.com/community/"
---
