---
baseURL: "/"
languageCode: "en-us"
title: "Replicated Help Center"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation and knowledgebase for Replicated."
googleAnalytics: "UA-61084834-1"

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"

  favicon: ""
  pagetitle: "Replicated"
  permalink: "#"

  docker_version_default: "17.06.0-ce"
  docker_version_minimum: "1.7.1"
  replicated_api_version_current: "2.10.4"
  replicated_latest_version: "2.10.4"
  replicated_latest_release_date: "August 22, 2017"

  swarm_docker_version_minimum: "1.13.1"
  swarm_docker_version_default: "17.06.0-ce"

taxonomies:
  category: "categories"
  tag: "tags"

algolia:
  index: "help_center"
  key: "0038e146bfecd33072d241b4b7c33279"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Guides"
      Weight: -100
      URL: "/guides/"
    - Name: "Documentation"
      Weight: -100
      URL: "/docs/"
    - Name: "API Reference"
      Weight: -100
      URL: "/categories/reference/"
---
