---
baseURL: "https://help.staging.replicated.com/"
languageCode: "en-us"
title: "Replicated Help Center"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation and knowledgebase for Replicated."
googleAnalytics: "UA-61084834-1"

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"
  search_env: "staging"

  matomo:
    host: "data-2.staging.replicated.com"
    site: "2"

  favicon: ""
  pagetitle: "Replicated"
  permalink: "#"

  docker_version_default: "19.03.8-ce"
  docker_version_minimum: "1.10.3"
  replicated_api_version_current: "2.51.0"
  replicated_latest_version: "2.51.0"
  replicated_latest_release_date: "February 22, 2021"

  swarm_docker_version_minimum: "1.13.1"
  swarm_docker_version_default: "19.03.8-ce"

  kubernetes_docker_version_minimum: "1.13.1"
  kubernetes_docker_version_default: "18.09.7"
  kubernetes_version: "1.15.12"

taxonomies:
  category: "categories"
  tag: "tags"
  kb-section: "kb-sections"

algolia:
  index: "help_center_staging"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Guides"
      Weight: 1
      URL: "/guides/"
    - Name: "Documentation"
      Weight: 2
      URL: "/docs/kubernetes/getting-started/overview/"
    - Name: "API Reference"
      Weight: 3
      URL: "/api/"
    - Name: "Community"
      Weight: 3
      URL: "https://help.replicated.com/community/"
---
